org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2

mod_version=3.6.2
maven_group=net.dawson.adorablehamsterpets
archives_base_name=adorablehamsterpets

geckolib_version=XZTmZlwb
modmenu_version=18.0.0
fzzy_config_version=0.7.6+26.1
patchouli_version=26.1-94-beta
jade_version=26.1.8+fabric
iris_version=1.11.3+26.1-fabric
placeholder_api_version=3.0.0+26.1
fabric_language_kotlin_version=1.13.13+kotlin.2.4.10
